{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ab62e33e-cb16-4bae-901c-ba5c211ce45c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Once upon a time there was a clockmaker named Miren who did not merely repair clocks—he mended moments. His little shop, painted the color of dusk, sat on a crooked lane where the cobbles remembered every footstep. People came to him with jars of things that had slipped: a laugh that had thinned to a whisper, the taste of a summer that had gone sour, the exact warmth of a hand now gone cold. Miren set them on his workbench like delicate gears and listened until the pieces told him how they wished to be put back together.\n",
      "\n",
      "He worked with tweezers made of patience and glue that smelled faintly of tea and rain. Some fragments were simple: a child’s surprise returned with the right tilt of a pivot. Others required a whole night of quiet, coaxing out color and sound the way one coaxes stars from a heavy sky. People left his shop lighter, clutching a pocketful of mended time, but always with the same warning in their eyes—that not every loss wanted repair, and some remedies demanded a price of forgetting.\n",
      "\n",
      "One autumn evening a woman came in carrying a very small, very ordinary thing: a pebble. She said it held the last laugh of her grandmother, and that without it the family’s dinners had begun to taste like bread without salt. Miren set the pebble beneath his lamp and soon realized the laugh had been threaded through a hundred other moments—stories, saucers, the smell of cabbage soup. To reweave it he would have to unpick everything around it, and someone else would forget to tell a story, or a soup would lose its warmth.\n",
      "\n",
      "Miren thought of how clocks keep time by surrendering seconds, how hands move only by yielding to the next tick. He understood then that to mend one thing perfectly might ruin another, and perfection was not always mercy. So he worked until dawn not to return the laugh as it had been, but to teach the household a new way of remembering—an evening tradition of saying one small thing aloud before dinner, so stories could take turns being remembered. The pebble’s laugh returned, softer and stranger, and at the table the first chuckle it sparked belonged not only to memory but to something newly made.\n",
      "\n",
      "From then on Miren still mended moments, but he also taught people how to live with the gaps—the spaces where new laughter and new stories could grow. And in his shop, where dusk always seemed to hang a little longer than outside, a tiny bell above the door chimed like a heartbeat whenever someone stepped in to leave a moment behind or to take one home.\n"
     ]
    }
   ],
   "source": [
    "from openai import OpenAI\n",
    "from dotenv import load_dotenv\n",
    "import os\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "client = OpenAI(\n",
    "    base_url=\"https://lucilia-genai-resource.services.ai.azure.com/openai/v1\",\n",
    "    api_key=os.getenv(\"AZURE_AI_API_KEY\")\n",
    ")\n",
    "\n",
    "response = client.responses.create(\n",
    "    model=\"gpt-5-mini\",\n",
    "    input=\"Complete the following: Once upon a time there was a\"\n",
    ")\n",
    "\n",
    "print(response.output_text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "dca194e2-0460-426e-9069-bd4dcb2f68de",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The capital of France is Paris.\n"
     ]
    }
   ],
   "source": [
    "from openai import OpenAI\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv(override=True)\n",
    "\n",
    "client = OpenAI(\n",
    "    base_url=os.getenv(\"AZURE_OPENAI_ENDPOINT\"),\n",
    "    api_key=os.getenv(\"AZURE_OPENAI_API_KEY\")\n",
    ")\n",
    "\n",
    "response = client.responses.create(\n",
    "    model=os.getenv(\"AZURE_OPENAI_DEPLOYMENT\"),\n",
    "    input=\"What is the capital of France? Answer in one sentence.\",\n",
    "    max_output_tokens=100\n",
    ")\n",
    "\n",
    "print(response.output_text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "f3420256-7066-4a26-a749-6c09d6e278fe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=======================================================\n",
      "CloudOps AI Assistant\n",
      "=======================================================\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Describe the technical issue:\n",
      "\n",
      " The API service started returning HTTP 503 errors after a production deployment. The application runs on Azure App Service.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Analyzing incident...\n",
      "\n",
      "## Incident Analysis\n",
      "\n",
      "### Root Cause\n",
      "- Deployment introduced an incompatible application instance or configuration causing the App Service to fail health checks and return 503 (service unavailable).\n",
      "\n",
      "### Possible Causes\n",
      "- New code crash on startup (unhandled exception) causing process to be unhealthy.\n",
      "- Missing or invalid environment/config settings (connection strings, feature flags) preventing initialization.\n",
      "- Deployment slot swap misconfiguration leading to incomplete rollout or warm-up failure.\n",
      "- Auto-heal or health check settings terminating instances during startup.\n",
      "- Under-provisioned plan or sudden resource exhaustion (memory/CPU) during deployment.\n",
      "- Dependency outage (database, cache, identity) causing app to respond 503 via readiness checks.\n",
      "\n",
      "### Recommended Actions\n",
      "- Roll back to last known-good deployment if rapid recovery needed.\n",
      "- Redeploy with diagnostic logging and enable Application Insights for exceptions and performance.\n",
      "- Validate environment variables, connection strings, and feature flags before deploy.\n",
      "- Configure proper warm-up and health check endpoints; use deployment slots with swap with preview.\n",
      "- Monitor App Service metrics (CPU, memory, requests, failed requests) and dependency health.\n",
      "- Implement automated smoke tests post-deploy.\n",
      "\n",
      "## Operational Runbook\n",
      "\n",
      "### Immediate Checks\n",
      "1. Check Azure App Service Health and Deployment Center status.\n",
      "2. Review App Service logs (stdout, event logs), Application Insights exceptions and failed requests.\n",
      "3. Verify App Service metrics: CPU, memory, HTTP 5xx/503 counts and instance restarts.\n",
      "\n",
      "### Investigation\n",
      "1. Inspect recent deployment artifacts, startup logs, and crash dumps for exceptions on boot.\n",
      "2. Check environment variables and connection strings in Configuration blade; confirm secrets accessible (Key Vault).\n",
      "3. Review slot swap operations, auto-heal rules, and health check endpoint responses across instances.\n",
      "\n",
      "### Resolution\n",
      "1. If root cause is bad code/config, perform rollback to previous deployment slot or restore from backup.\n",
      "2. Fix configuration or dependency issues; redeploy and monitor warm-up/health checks.\n",
      "3. If resource exhaustion, scale up/out App Service Plan temporarily and investigate memory/CPU leaks; adjust autoscale rules.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "\n",
    "from dotenv import load_dotenv\n",
    "from openai import OpenAI\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "client = OpenAI(\n",
    "    base_url=os.getenv(\"AZURE_OPENAI_ENDPOINT\"),\n",
    "    api_key=os.getenv(\"AZURE_OPENAI_API_KEY\")\n",
    ")\n",
    "\n",
    "deployment_name = os.getenv(\"AZURE_OPENAI_DEPLOYMENT\")\n",
    "\n",
    "\n",
    "def analyze_incident(incident):\n",
    "\n",
    "    system_prompt = \"\"\"\n",
    "You are a Senior Cloud Operations Engineer.\n",
    "\n",
    "Analyze the incident.\n",
    "\n",
    "Return EXACTLY this format.\n",
    "\n",
    "## Incident Analysis\n",
    "\n",
    "### Root Cause\n",
    "- ...\n",
    "\n",
    "### Possible Causes\n",
    "- ...\n",
    "- ...\n",
    "- ...\n",
    "\n",
    "### Recommended Actions\n",
    "- ...\n",
    "- ...\n",
    "- ...\n",
    "\n",
    "## Operational Runbook\n",
    "\n",
    "### Immediate Checks\n",
    "1.\n",
    "2.\n",
    "3.\n",
    "\n",
    "### Investigation\n",
    "1.\n",
    "2.\n",
    "3.\n",
    "\n",
    "### Resolution\n",
    "1.\n",
    "2.\n",
    "3.\n",
    "\n",
    "Rules:\n",
    "- Short answers.\n",
    "- Maximum 250 words.\n",
    "- Use bullet points.\n",
    "- No introductions.\n",
    "- No conclusions.\n",
    "\"\"\"\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=deployment_name,\n",
    "        messages=[\n",
    "            {\n",
    "                \"role\": \"system\",\n",
    "                \"content\": system_prompt\n",
    "            },\n",
    "            {\n",
    "                \"role\": \"user\",\n",
    "                \"content\": incident\n",
    "            }\n",
    "        ],\n",
    "        reasoning_effort=\"minimal\",\n",
    "        verbosity=\"low\",\n",
    "        max_completion_tokens=450\n",
    "    )\n",
    "\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "\n",
    "def main():\n",
    "\n",
    "    print(\"=\" * 55)\n",
    "    print(\"IT Assistant\")\n",
    "    print(\"=\" * 55)\n",
    "\n",
    "    incident = input(\"\\nDescribe the technical issue:\\n\\n\")\n",
    "\n",
    "    print(\"\\nAnalyzing incident...\\n\")\n",
    "\n",
    "    result = analyze_incident(incident)\n",
    "\n",
    "    print(result)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7eb6fe2f-9da5-481b-a91c-9e562bca2eca",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.12 (ai-env)",
   "language": "python",
   "name": "ai-env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
